#============ tomcat配置#====================================
server:
  servlet:
    context-path: /money
  port: 8080
#============ 数据库配置#====================================
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/money
    username: root
    password: 123456
    # 使用druid数据源
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.jdbc.Driver
    filters: stat
    maxActive: 20
    initialSize: 1
    maxWait: 60000
    minIdle: 1
    timeBetweenEvictionRunsMillis: 60000
    minEvictableIdleTimeMillis: 300000
    validationQuery: select 'x'
    testWhileIdle: true
    testOnBorrow: false
    testOnReturn: false
    poolPreparedStatements: true
    maxOpenPreparedStatements: 20
#============ 热部署生效#====================================  
#  devtools:
#    restart:
#      enabled: true
#      #设置重启的目录
#      additional-paths: src/main
#      #exclude配置目录下的文件夹内容修改不重启
#      #exclude: 
# spring mvc 视图解析器
  mvc:
    view:
      prefix: /index/
      suffix: .jsp      

#============ mybatis配置#====================================
mybatis:
  mapperLocations: classpath:mapping/*.xml
  type-aliases-package: cn.com.project.domain  #对应实体类对象
  
#pagehelper分页插件
pagehelper:
    helperDialect: mysql
    reasonable: true
    supportMethodsArguments: true
    params: count=countSql  
#==================== 日志配合·标准  ============================
logging:
  name: money
  config: classpath:logback-spring.xml
  path: logs/money
  level: 
    root: info
      